import type { Metadata } from 'next';
import { Poppins, Inter } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Header from './components/layout/Header';
import { Button } from '@/components/ui/button';
import { SignInButton, SignUpButton } from '@clerk/nextjs';
import Footer from './components/layout/Footer';

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '600'], // Angi vekter du vil bruke
	variable: '--font-poppins', // Legg til en CSS-variabel (valgfritt)
});

const inter = Inter({
	subsets: ['latin'],
	weight: ['400', '700'], // Angi vekter du vil bruke
	variable: '--font-inter', // Legg til en CSS-variabel (valgfritt)
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body
					className={`${poppins.variable} ${inter.variable} antialiased flex flex-col min-h-screen`}
				>
					<header className='fixed top-0 left-0 w-full flex justify-between items-center mx-auto container py-6 z-50'>
						<p>Logo Bærum Padel</p>
						<Header />
					</header>
					<div className='pt-[96px]'>{children}</div>
					<Footer />
				</body>
			</html>
		</ClerkProvider>
	);
}
