import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Header from './components/Header';
import { Button } from '@/components/ui/button';
import { SignInButton, SignUpButton } from '@clerk/nextjs';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
				>
					<header className='flex w-full justify-between items-center mx-auto container mt-6'>
						<p>Logo Bærum Padel</p>
						<Header />
						<div className='flex gap-2'>
							<Button asChild>
								<SignInButton>Logg inn</SignInButton>
							</Button>
							<Button asChild variant='outline'>
								<SignUpButton>Registrer deg</SignUpButton>
							</Button>
						</div>
					</header>
					<>{children}</>
				</body>
			</html>
		</ClerkProvider>
	);
}
